# Generated by Django 3.0.2 on 2020-02-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='member/profile_image')),
                ('profile_name', models.CharField(max_length=32)),
                ('position', models.CharField(choices=[('Professor', 'Professor'), ('Lab Master', 'Lab Master'), ('Lab Member', 'Lab Member'), ('Graduate', 'Graduate')], max_length=32)),
                ('description', models.TextField()),
            ],
        ),
    ]
