# Generated by Django 3.0.2 on 2020-02-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='member/profile_image')),
                ('profile_name', models.CharField(max_length=32)),
                ('position', models.CharField(choices=[('0', 'Professor'), ('1', 'Lab Master'), ('2', 'Lab Manager'), ('3', 'Lab Member'), ('4', 'Graduate')], max_length=32)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='project/thumbnail')),
                ('title', models.CharField(max_length=32)),
                ('detail', models.TextField()),
            ],
        ),
    ]
