# Generated by Django 3.0.2 on 2020-02-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200217_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
